apiVersion: v1
kind: Namespace
metadata:
  name: kappa-iot
---
# ServiceAccount for Spark (adapted from original rbac.yaml)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: kappa-iot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-role-kappa
subjects:
  - kind: ServiceAccount
    name: spark
    namespace: kappa-iot
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
