# Spark Streaming Job (Speed Layer)
# Run with: kubectl apply -f spark-job.yaml -n kappa-iot
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-iot-streaming
  namespace: kappa-iot
spec:
  template:
    spec:
      serviceAccountName: spark
      restartPolicy: OnFailure
      containers:
        - name: spark-driver
          image: bitnami/spark:3.5
          command:
            - spark-submit
            - --master
            - k8s://https://kubernetes.default.svc
            - --deploy-mode
            - client
            - --name
            - iot-kappa-streaming
            - --packages
            - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0,org.apache.hadoop:hadoop-aws:3.3.4
            - --conf
            - spark.kubernetes.namespace=kappa-iot
            - --conf
            - spark.kubernetes.container.image=bitnami/spark:3.5
            - --conf
            - spark.executor.instances=2
            - /opt/spark-app/spark_streaming_app.py
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "iot-sensor-topic"
            - name: MINIO_ENDPOINT
              value: "http://minio-service:9000"
            - name: MINIO_ACCESS
              value: "minioadmin"
            - name: MINIO_SECRET
              value: "minioadmin"
            - name: MINIO_BUCKET
              value: "iot-output"
