apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-server
  namespace: kappa-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: streaming-server-pod
  template:
    metadata:
      labels:
        pod: streaming-server-pod
    spec:
      containers:
        - name: streaming-server-container
          image: localhost:5000/streaming-server:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              value: "kafka-service:9092"
            - name: KAFKA_TOPIC
              value: "iot-sensor-topic"
